import type { InternalNote } from "@/types";

export const NOTES: InternalNote[] = [
  {
    id: "note-001",
    clientId: "cl-001",
    applicationId: "ap-001",
    text: "Cliente confirmó que la empresa realiza descuento directo desde el próximo periodo de pago.",
    authorId: "u-004",
    createdAt: "2026-07-28T10:15:00-05:00",
    type: "seguimiento",
    priority: "media",
  },
  {
    id: "note-002",
    clientId: "cl-001",
    applicationId: "ap-001",
    text: "Falta ficha de la CSS actualizada, se solicitó por correo el 2 de agosto.",
    authorId: "u-004",
    createdAt: "2026-08-02T14:22:00-05:00",
    type: "documentacion",
    priority: "alta",
  },
  {
    id: "note-003",
    clientId: "cl-002",
    applicationId: "ap-002",
    text: "Documentación completa. Lista para pasar a comité de evaluación esta semana.",
    authorId: "u-005",
    createdAt: "2026-08-03T09:12:00-05:00",
    type: "evaluacion",
    priority: "media",
  },
  {
    id: "note-004",
    clientId: "cl-003",
    applicationId: "ap-003",
    text: "Se llamó al cliente para solicitar carta de trabajo y comprobante de pago pendientes.",
    authorId: "u-004",
    createdAt: "2026-08-01T11:05:00-05:00",
    type: "llamada",
    priority: "media",
  },
  {
    id: "note-005",
    clientId: "cl-004",
    applicationId: "ap-004",
    text: "Solicitud aprobada por comité. Coordinar firma y desembolso con el cliente.",
    authorId: "u-006",
    createdAt: "2026-07-28T16:50:00-05:00",
    type: "importante",
    priority: "alta",
  },
  {
    id: "note-006",
    clientId: "cl-005",
    applicationId: "ap-005",
    text: "Cliente presenta incumplimiento previo reportado por otra sucursal. Se registra restricción interna.",
    authorId: "u-005",
    createdAt: "2026-07-20T10:35:00-05:00",
    type: "importante",
    priority: "alta",
  },
  {
    id: "note-007",
    clientId: "cl-006",
    applicationId: "ap-006",
    text: "Todos los documentos recibidos. Programada evaluación de crédito para la próxima semana.",
    authorId: "u-004",
    createdAt: "2026-08-03T13:20:00-05:00",
    type: "seguimiento",
    priority: "baja",
  },
  {
    id: "note-008",
    clientId: "cl-007",
    applicationId: "ap-007",
    text: "Se contactó a la empresa para confirmar referencias laborales del cliente.",
    authorId: "u-006",
    createdAt: "2026-08-02T09:00:00-05:00",
    type: "llamada",
    priority: "media",
  },
  {
    id: "note-009",
    clientId: "cl-009",
    applicationId: "ap-009",
    text: "Expediente cerrado. Cliente aprobado, en seguimiento post-desembolso.",
    authorId: "u-004",
    createdAt: "2026-07-15T12:05:00-05:00",
    type: "general",
    priority: "baja",
  },
  {
    id: "note-010",
    clientId: "cl-011",
    applicationId: "ap-010",
    text: "Primer contacto realizado. Cliente interesado, se enviará lista de requisitos.",
    authorId: "u-005",
    createdAt: "2026-07-21T09:35:00-05:00",
    type: "general",
    priority: "baja",
  },
  {
    id: "note-011",
    clientId: "cl-012",
    applicationId: "ap-011",
    text: "Comprobante de pago recibido, en revisión. Faltan recibo de servicios y confirmación de descuento.",
    authorId: "u-004",
    createdAt: "2026-08-01T17:15:00-05:00",
    type: "documentacion",
    priority: "media",
  },
  {
    id: "note-012",
    clientId: "cl-013",
    applicationId: "ap-012",
    text: "Cliente solicitó cancelar el trámite por motivos personales.",
    authorId: "u-006",
    createdAt: "2026-04-02T10:05:00-05:00",
    type: "general",
    priority: "baja",
  },
  {
    id: "note-013",
    clientId: "cl-014",
    applicationId: "ap-013",
    text: "Cliente con excelente historial. Aprobado sin observaciones.",
    authorId: "u-005",
    createdAt: "2026-07-22T11:45:00-05:00",
    type: "evaluacion",
    priority: "baja",
  },
  {
    id: "note-014",
    clientId: "cl-016",
    applicationId: "ap-014",
    text: "Recibo de servicios presentado está a nombre de un familiar; se solicitó actualización.",
    authorId: "u-006",
    createdAt: "2026-07-31T14:05:00-05:00",
    type: "documentacion",
    priority: "media",
  },
  {
    id: "note-015",
    clientId: "cl-010",
    text: "Cliente inactivo desde febrero, sin respuesta a los últimos dos intentos de contacto.",
    authorId: "u-006",
    createdAt: "2026-06-01T10:00:00-05:00",
    type: "seguimiento",
    priority: "baja",
  },
  {
    id: "note-016",
    clientId: "cl-017",
    text: "Cliente activo, sin solicitudes en curso. Se mantiene en cartera para seguimiento comercial.",
    authorId: "u-005",
    createdAt: "2026-07-01T09:00:00-05:00",
    type: "general",
    priority: "baja",
  },
];

export function getNotesByClientId(clientId: string): InternalNote[] {
  return NOTES.filter((note) => note.clientId === clientId).sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
  );
}
